---
- name: Check if site is already installed.
  command: >
    {{ drush_path }} status bootstrap
    chdir={{ drupal_core_path }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false
  sudo: no

- name: Install Drupal with drush.
  command: >
    {{ drush_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ mysql_databases[0].name }}
    chdir={{ drupal_core_path }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"
  sudo: no

- name: Create a writable files directory for current drupal site.
  file: path={{ drupal_core_path }}/sites/{{ drupal_site_directory }}/files state=directory owner=www-data group=www-data mode=0775

- name: Install configured modules with drush.
  command: >
    {{ drush_path }} pm-enable -y {{ drupal_enable_modules | join(" ") }}
    chdir={{ drupal_core_path }}
  when: "'Successful' not in drupal_site_installed.stdout"
  sudo: no

- name: Clean out theme folder.
  file: path={{ drupal_core_path }}/sites/all/themes state=absent
  when: drupal_theme_repository is defined

- name: Checkout theme repository if provided.
  git: >
    repo={{ drupal_theme_repository }}
    dest={{ drupal_core_path }}/sites/all/themes/
    version={{ drupal_theme_version }}
    accept_hostkey=yes
    force=yes
    recursive=no
  when: drupal_theme_repository is defined and drupal_theme_key is not defined

- name: Checkout theme repository (with SSH key) if provided.
  git: >
    repo={{ drupal_theme_repository }}
    dest={{ drupal_core_path }}/sites/all/themes/
    version={{ drupal_theme_version }}
    accept_hostkey=yes
    force=yes
    recursive=no
    key_file={{ drupal_theme_key }}
  when: drupal_theme_repository is defined and drupal_theme_key is defined
